apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-redis-replicas-1
  labels: 
    app: pvc-data-redis-replicas-1
    replica: "1"
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /opt/redis/replica/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-1
  storageClassName: local-storage  