apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-redis-master-0
  namespace: redis
  labels:
    app: pvc-data-redis-master-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi
  volumeName: pv-data-redis-master-0